version: '3'
services:

  front-react:
    build:
      context: ./client
      dockerfile: Dockerfile-dev

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:3000"

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile-dev

    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./var/www/html/files:/var/www/html/files
      - ./server:/server
      - /server/node_modules

  db-dev:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=squadhelp-dev
    ports:
      - "2345:5432"

volumes:
  server-dev:
