version: '3'
services:

  client-prod:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server-prod
    volumes_from:
      - server-prod:ro

  server-prod:
    build:
      context: ./server
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db-prod
    volumes:
      - /var/www/html/images:/var/www/html/images
      - /var/www/html/files:/var/www/html/files

  db-prod:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=squadhelp-prod
    ports:
      - "5432:5432"

volumes:
  server-prod:
  nginx-server-prod:
